name: newtorch
channels:
  - defaults
dependencies:
  - _r-mutex=1.0.0=anacondar_1
  - anyio=4.2.0=py312haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h2bbff1b_0
  - async-lru=2.0.4=py312haa95532_0
  - attrs=23.1.0=py312haa95532_0
  - babel=2.11.0=py312haa95532_0
  - beautifulsoup4=4.12.3=py312haa95532_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotli-python=1.0.9=py312hd77b12b_8
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.7.2=haa95532_0
  - certifi=2024.8.30=py312haa95532_0
  - cffi=1.16.0=py312h2bbff1b_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cloudpickle=3.0.0=py312haa95532_0
  - colorama=0.4.6=py312haa95532_0
  - comm=0.2.1=py312haa95532_0
  - debugpy=1.6.7=py312hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - expat=2.6.3=h5da7b33_0
  - h11=0.14.0=py312haa95532_0
  - httpcore=1.0.2=py312haa95532_0
  - httpx=0.27.0=py312haa95532_0
  - idna=3.7=py312haa95532_0
  - ipykernel=6.28.0=py312haa95532_0
  - ipython=8.27.0=py312haa95532_0
  - jedi=0.19.1=py312haa95532_0
  - jinja2=3.1.4=py312haa95532_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py312haa95532_0
  - jsonschema-specifications=2023.7.1=py312haa95532_0
  - jupyter-lsp=2.2.0=py312haa95532_0
  - jupyter_client=8.6.0=py312haa95532_0
  - jupyter_core=5.7.2=py312haa95532_0
  - jupyter_events=0.10.0=py312haa95532_0
  - jupyter_server=2.14.1=py312haa95532_0
  - jupyter_server_terminals=0.4.4=py312haa95532_1
  - jupyterlab=4.2.5=py312haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py312haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.18=h62dcd97_0
  - m2w64-bwidget=1.9.10=2
  - m2w64-bzip2=1.0.6=6
  - m2w64-expat=2.1.1=2
  - m2w64-fftw=3.3.4=6
  - m2w64-flac=1.3.1=3
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-gsl=2.1=2
  - m2w64-libiconv=1.14=6
  - m2w64-libjpeg-turbo=1.4.2=3
  - m2w64-libogg=1.3.2=3
  - m2w64-libpng=1.6.21=2
  - m2w64-libsndfile=1.0.26=2
  - m2w64-libsodium=1.0.10=2
  - m2w64-libtiff=4.0.6=2
  - m2w64-libvorbis=1.3.5=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-libxml2=2.9.3=4
  - m2w64-mpfr=3.1.4=4
  - m2w64-openblas=0.2.19=1
  - m2w64-pcre=8.38=2
  - m2w64-speex=1.2rc2=3
  - m2w64-speexdsp=1.2rc3=3
  - m2w64-tcl=8.6.5=3
  - m2w64-tk=8.6.5=3
  - m2w64-tktable=2.10=5
  - m2w64-wineditline=2.101=5
  - m2w64-xz=5.2.2=2
  - m2w64-zeromq=4.1.4=2
  - m2w64-zlib=1.2.8=10
  - markupsafe=2.1.3=py312h2bbff1b_0
  - matplotlib-inline=0.1.6=py312haa95532_0
  - mistune=2.0.4=py312haa95532_0
  - msys2-conda-epoch=20160418=1
  - nbclient=0.8.0=py312haa95532_0
  - nbconvert=7.10.0=py312haa95532_0
  - nbformat=5.9.2=py312haa95532_0
  - nest-asyncio=1.6.0=py312haa95532_0
  - notebook=7.2.2=py312haa95532_0
  - notebook-shim=0.2.3=py312haa95532_0
  - openssl=3.0.15=h827c3e9_0
  - overrides=7.4.0=py312haa95532_0
  - packaging=24.1=py312haa95532_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pip=24.2=py312haa95532_0
  - prometheus_client=0.14.1=py312haa95532_0
  - prompt-toolkit=3.0.43=py312haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py312h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py312haa95532_1
  - pysocks=1.7.1=py312haa95532_0
  - python=3.12.5=h14ffc60_1
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-fastjsonschema=2.16.2=py312haa95532_0
  - python-json-logger=2.0.7=py312haa95532_0
  - pytz=2024.1=py312haa95532_0
  - pywin32=305=py312h2bbff1b_0
  - pywinpty=2.0.10=py312h5da7b33_0
  - pyyaml=6.0.1=py312h2bbff1b_0
  - pyzmq=25.1.2=py312hd77b12b_0
  - r-askpass=1.0=r36_0
  - r-assertthat=0.2.1=r36h6115d3f_0
  - r-backports=1.1.4=r36h6115d3f_0
  - r-base=3.6.1=hf18239d_1
  - r-base64enc=0.1_3=r36h6115d3f_4
  - r-bh=1.69.0_1=r36h6115d3f_0
  - r-boot=1.3_20=r36h6115d3f_0
  - r-broom=0.5.2=r36h6115d3f_0
  - r-callr=3.2.0=r36h6115d3f_0
  - r-caret=6.0_83=r36h6115d3f_0
  - r-cellranger=1.1.0=r36h6115d3f_0
  - r-class=7.3_15=r36h6115d3f_0
  - r-cli=1.1.0=r36h6115d3f_0
  - r-clipr=0.6.0=r36h6115d3f_0
  - r-cluster=2.0.8=r36h6115d3f_0
  - r-codetools=0.2_16=r36h6115d3f_0
  - r-colorspace=1.4_1=r36h6115d3f_0
  - r-crayon=1.3.4=r36h6115d3f_0
  - r-curl=3.3=r36h6115d3f_0
  - r-data.table=1.12.2=r36h6115d3f_0
  - r-dbi=1.0.0=r36h6115d3f_0
  - r-dbplyr=1.4.0=r36h6115d3f_0
  - r-dichromat=2.0_0=r36h6115d3f_4
  - r-digest=0.6.18=r36h6115d3f_0
  - r-dplyr=0.8.0.1=r36h6115d3f_0
  - r-ellipsis=0.1.0=r36h6115d3f_0
  - r-essentials=3.6.0=r36_0
  - r-evaluate=0.13=r36h6115d3f_0
  - r-fansi=0.4.0=r36h6115d3f_0
  - r-forcats=0.4.0=r36h6115d3f_0
  - r-foreach=1.4.4=r36h6115d3f_0
  - r-foreign=0.8_71=r36h6115d3f_0
  - r-formatr=1.6=r36h6115d3f_0
  - r-fs=1.2.7=r36h6115d3f_0
  - r-generics=0.0.2=r36h6115d3f_0
  - r-ggplot2=3.1.1=r36h6115d3f_0
  - r-glmnet=2.0_16=r36h6115d3f_0
  - r-glue=1.3.1=r36h6115d3f_0
  - r-gower=0.2.0=r36h6115d3f_0
  - r-gtable=0.3.0=r36h6115d3f_0
  - r-haven=2.1.0=r36h6115d3f_0
  - r-hexbin=1.27.2=r36h6115d3f_0
  - r-highr=0.8=r36h6115d3f_0
  - r-hms=0.4.2=r36h6115d3f_0
  - r-htmltools=0.3.6=r36h6115d3f_0
  - r-htmlwidgets=1.3=r36h6115d3f_0
  - r-httpuv=1.5.1=r36h6115d3f_0
  - r-httr=1.4.0=r36h6115d3f_0
  - r-ipred=0.9_8=r36h6115d3f_0
  - r-irdisplay=0.7.0=r36h6115d3f_0
  - r-irkernel=0.8.15=r36_0
  - r-iterators=1.0.10=r36h6115d3f_0
  - r-jsonlite=1.6=r36h6115d3f_0
  - r-kernsmooth=2.23_15=r36h6115d3f_4
  - r-knitr=1.22=r36h6115d3f_0
  - r-labeling=0.3=r36h6115d3f_4
  - r-later=0.8.0=r36h6115d3f_0
  - r-lattice=0.20_38=r36h6115d3f_0
  - r-lava=1.6.5=r36h6115d3f_0
  - r-lazyeval=0.2.2=r36h6115d3f_0
  - r-lubridate=1.7.4=r36h6115d3f_0
  - r-magrittr=1.5=r36h6115d3f_4
  - r-maps=3.3.0=r36h6115d3f_0
  - r-markdown=0.9=r36h6115d3f_0
  - r-mass=7.3_51.3=r36h6115d3f_0
  - r-matrix=1.2_17=r36h6115d3f_0
  - r-mgcv=1.8_28=r36h6115d3f_0
  - r-mime=0.6=r36h6115d3f_0
  - r-modelmetrics=1.2.2=r36h6115d3f_0
  - r-modelr=0.1.4=r36h6115d3f_0
  - r-munsell=0.5.0=r36h6115d3f_0
  - r-nlme=3.1_139=r36h6115d3f_0
  - r-nnet=7.3_12=r36h6115d3f_0
  - r-numderiv=2016.8_1=r36h6115d3f_0
  - r-openssl=1.3=r36h6115d3f_0
  - r-pbdzmq=0.3_3=r36h6115d3f_0
  - r-pillar=1.3.1=r36h6115d3f_0
  - r-pkgconfig=2.0.2=r36h6115d3f_0
  - r-plogr=0.2.0=r36h6115d3f_0
  - r-plyr=1.8.4=r36h6115d3f_0
  - r-prettyunits=1.0.2=r36h6115d3f_0
  - r-processx=3.3.0=r36h6115d3f_0
  - r-prodlim=2018.04.18=r36h6115d3f_0
  - r-progress=1.2.0=r36h6115d3f_0
  - r-promises=1.0.1=r36h6115d3f_0
  - r-ps=1.3.0=r36h6115d3f_0
  - r-purrr=0.3.2=r36h6115d3f_0
  - r-quantmod=0.4_14=r36h6115d3f_0
  - r-r6=2.4.0=r36h6115d3f_0
  - r-randomforest=4.6_14=r36h6115d3f_0
  - r-rbokeh=0.6.3=r36_0
  - r-rcolorbrewer=1.1_2=r36h6115d3f_0
  - r-rcpp=1.0.1=r36h6115d3f_0
  - r-rcpproll=0.3.0=r36h6115d3f_0
  - r-readr=1.3.1=r36h6115d3f_0
  - r-readxl=1.3.1=r36h6115d3f_0
  - r-recipes=0.1.5=r36h6115d3f_0
  - r-recommended=3.6.0=r36_0
  - r-rematch=1.0.1=r36h6115d3f_0
  - r-repr=0.19.2=r36h6115d3f_0
  - r-reprex=0.2.1=r36h6115d3f_0
  - r-reshape2=1.4.3=r36h6115d3f_0
  - r-rlang=0.3.4=r36h6115d3f_0
  - r-rmarkdown=1.12=r36h6115d3f_0
  - r-rpart=4.1_15=r36h6115d3f_0
  - r-rstudioapi=0.10=r36h6115d3f_0
  - r-rvest=0.3.3=r36h6115d3f_0
  - r-scales=1.0.0=r36h6115d3f_0
  - r-selectr=0.4_1=r36h6115d3f_0
  - r-shiny=1.3.2=r36h6115d3f_0
  - r-sourcetools=0.1.7=r36h6115d3f_0
  - r-spatial=7.3_11=r36h6115d3f_4
  - r-squarem=2017.10_1=r36h6115d3f_0
  - r-stringi=1.4.3=r36h6115d3f_0
  - r-stringr=1.4.0=r36h6115d3f_0
  - r-survival=2.44_1.1=r36h6115d3f_0
  - r-sys=3.2=r36h6115d3f_0
  - r-tibble=2.1.1=r36h6115d3f_0
  - r-tidyr=0.8.3=r36h6115d3f_0
  - r-tidyselect=0.2.5=r36h6115d3f_0
  - r-tidyverse=1.2.1=r36h6115d3f_0
  - r-timedate=3043.102=r36h6115d3f_0
  - r-tinytex=0.12=r36h6115d3f_0
  - r-ttr=0.23_4=r36h6115d3f_0
  - r-utf8=1.1.4=r36h6115d3f_0
  - r-uuid=0.1_2=r36h6115d3f_4
  - r-viridislite=0.3.0=r36h6115d3f_0
  - r-whisker=0.3_2=r36h6115d3f_4
  - r-withr=2.1.2=r36h6115d3f_0
  - r-xfun=0.6=r36h6115d3f_0
  - r-xml2=1.2.0=r36h6115d3f_0
  - r-xtable=1.8_4=r36h6115d3f_0
  - r-xts=0.11_2=r36h6115d3f_0
  - r-yaml=2.2.0=r36h6115d3f_0
  - r-zoo=1.8_5=r36h6115d3f_0
  - referencing=0.30.2=py312haa95532_0
  - requests=2.32.3=py312haa95532_0
  - rfc3339-validator=0.1.4=py312haa95532_0
  - rfc3986-validator=0.1.1=py312haa95532_0
  - rpds-py=0.10.6=py312h062c2fa_0
  - send2trash=1.8.2=py312haa95532_0
  - setuptools=72.1.0=py312haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h2bbff1b_0
  - tk=8.6.14=h0416ee5_0
  - tornado=6.4.1=py312h827c3e9_0
  - traitlets=5.14.3=py312haa95532_0
  - typing-extensions=4.11.0=py312haa95532_0
  - typing_extensions=4.11.0=py312haa95532_0
  - tzdata=2024a=h04d1e81_0
  - urllib3=2.2.2=py312haa95532_0
  - vc=14.40=h2eaa2aa_1
  - vs2015_runtime=14.40.33807=h98bb1dd_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py312haa95532_2
  - websocket-client=1.8.0=py312haa95532_0
  - wheel=0.44.0=py312haa95532_0
  - win_inet_pton=1.1.0=py312haa95532_0
  - winpty=0.4.3=4
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=hd77b12b_0
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - asttokens==2.4.1
      - executing==2.1.0
      - mouseinfo==0.1.3
      - onnx==1.16.2
      - platformdirs==4.3.6
      - pyautogui==0.9.54
      - pygetwindow==0.0.9
      - pymsgbox==1.0.9
      - pyperclip==1.9.0
      - pyrect==0.2.0
      - pyscreeze==1.0.1
      - pytweening==1.2.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - spyder-kernels==3.0.0
      - stack-data==0.6.3
      - sympy==1.13.3
      - terminado==0.18.1
      - tinycss2==1.3.0
prefix: E:\conda\envs\newtorch
